# Generated by Django 4.0 on 2023-05-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
