# Generated by Django 4.0 on 2023-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_alter_cart_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pspec',
            field=models.IntegerField(default=0, verbose_name='產品規格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='PNUM',
            field=models.IntegerField(verbose_name='數量'),
        ),
    ]
