# Generated by Django 4.0 on 2023-05-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.CharField(blank=True, max_length=1000, unique=True, verbose_name='購物車編號')),
                ('MID', models.CharField(max_length=1000, verbose_name='會員編號')),
                ('PID', models.CharField(max_length=1000, verbose_name='產品編號')),
                ('NUM', models.IntegerField(verbose_name='數量')),
            ],
        ),
    ]
