# Generated by Django 4.0 on 2023-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('CID', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='購物車編號')),
                ('MID', models.CharField(max_length=1000, verbose_name='會員編號')),
                ('PID', models.CharField(max_length=1000, verbose_name='產品編號')),
                ('NUM', models.IntegerField(max_length=20, verbose_name='數量')),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('MID', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='會員編號')),
                ('MName', models.CharField(max_length=20, verbose_name='會員姓名')),
                ('MPhone', models.CharField(max_length=50, verbose_name='會員電話')),
                ('MPW', models.CharField(max_length=20, verbose_name='會員密碼')),
                ('MAccount', models.CharField(max_length=50, verbose_name='會員帳號')),
                ('MEmail', models.CharField(max_length=100, verbose_name='會員信箱')),
                ('MAddr', models.CharField(max_length=100, verbose_name='會員地址')),
                ('MVISA', models.CharField(max_length=100, null=True, verbose_name='會員信用卡號')),
                ('MCK', models.CharField(max_length=100, verbose_name='信用卡到期日')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('OID', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='訂單編號')),
                ('MID', models.CharField(max_length=1000, verbose_name='會員編號')),
                ('PID', models.CharField(max_length=1000, verbose_name='產品編號')),
                ('PNUM', models.IntegerField(verbose_name='消費點數')),
                ('ODate', models.DateField(auto_now_add=True, verbose_name='訂單日期')),
                ('OAddr', models.CharField(max_length=100, verbose_name='配送地址')),
                ('OStatus', models.CharField(choices=[('NOT_SHIPPED', '尚未出貨'), ('SHIPPED', '已出貨'), ('ARRIVED', '已抵達')], default='NOT_SHIPPED', max_length=12, verbose_name='訂單狀態')),
                ('OPayment', models.CharField(choices=[('COD', '貨到付款'), ('CC', '刷卡'), ('CVS', '超商')], default='COD', max_length=3, verbose_name='付款方式')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('PID', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='產品編號')),
                ('PPrice', models.IntegerField(verbose_name='產品價錢')),
                ('PName', models.CharField(max_length=100, verbose_name='產品名稱')),
                ('PDetail', models.CharField(max_length=10000, verbose_name='產品內容')),
                ('PStatus', models.CharField(choices=[('IN_STOCK', '上架'), ('OUT_OF_STOCK', '下架'), ('UNAVAILABLE', '缺貨')], default='IN_STOCK', max_length=13, verbose_name='產品狀態')),
                ('PPhoto', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='產品圖片')),
                ('PCategory', models.CharField(max_length=20, verbose_name='產品分類')),
            ],
        ),
    ]
