# Generated by Django 4.0 on 2023-06-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('managerID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='使用者名稱')),
                ('password', models.CharField(max_length=100, verbose_name='密碼')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Pnum',
            field=models.IntegerField(default=0, verbose_name='產品數量'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='ODID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='訂單明細編號'),
        ),
    ]
