# Generated by Django 4.0 on 2023-06-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pnum',
            field=models.IntegerField(default=0, verbose_name='產品數量'),
        ),
    ]
