# Generated by Django 4.1.3 on 2023-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywebsite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="fav",
            fields=[
                ("FID", models.AutoField(primary_key=True, serialize=False)),
                ("MID", models.CharField(max_length=1000, verbose_name="會員編號")),
                ("PID", models.CharField(max_length=1000, verbose_name="產品編號")),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="PID",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="產品編號"
            ),
        ),
    ]
