# Generated by Django 4.0 on 2023-06-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_product_pnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='ODID',
            field=models.AutoField(max_length=1000, primary_key=True, serialize=False, verbose_name='訂單明細編號'),
        ),
    ]
