# Generated by Django 4.0.4 on 2023-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_alter_cart_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='MAddr',
            field=models.CharField(max_length=100, null=True, verbose_name='會員地址'),
        ),
        migrations.AlterField(
            model_name='member',
            name='MCK',
            field=models.CharField(max_length=100, null=True, verbose_name='信用卡到期日'),
        ),
        migrations.AlterField(
            model_name='member',
            name='MID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='會員編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='PNUM',
            field=models.IntegerField(verbose_name='數量'),
        ),
    ]
