# Generated by Django 4.1.3 on 2023-06-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mywebsite", "0002_manager_product_pnum_alter_order_detail_odid"),
        ("mywebsite", "0003_alter_order_detail_odid"),
        ("mywebsite", "0004_alter_cart_cid"),
    ]

    operations = []
