# Generated by Django 4.1.3 on 2023-07-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mywebsite", "0002_alter_product_pid"),
        ("mywebsite", "0005_merge_20230626_1606"),
    ]

    operations = []
